version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - emotions
    env_file: .env
    ports:
      - 5432:5432

  backend:
    image: stargazer87/backend
    networks:
      - emotions
    env_file: .env
    ports:
      - 5000:5000

  vk_handler:
      image: stargazer87/vk_wall_handler
      networks:
        - emotions
      env_file: .env
      ports:
        - 5000:5000

  bot:
    image: stargazer87/tgbot
    networks:
      - emotions
    env_file: .env
    ports:
      - 5434:5434

networks:
  emotions: