version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - emotions
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    image: stargazer87/backend
    networks:
      - emotions
    env_file: .env
    ports:

  vk_wall_handler:
      image: stargazer87/vk_wall_handler
      networks:
        - emotions
      env_file: .env
        
  emotion_recogniser:
      image: stargazer87/emotion_recogniser
      networks:
        - emotions
      env_file: .env

  tgbot:
    image: stargazer87/tgbot
    networks:
      - emotions
    env_file: .env

networks:
  emotions: